version: '3.8'

services:
  rtrw-app:
    build: .
    container_name: rtrw-app
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production

  rtrw-backend:
    build: ./backend
    container_name: rtrw-backend
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - rtrw-database
    environment:
      - NODE_ENV=production
      - DB_HOST=rtrw-database
      - DB_PORT=3306
      - DB_NAME=rtrw_db
      - DB_USER=root
      - DB_PASSWORD=password

  rtrw-database:
    image: mysql:8.0
    container_name: rtrw-database
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rtrw_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./rtrw_db\ \(1\).sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
